"""
You are given a JSON file containing performance data for several Facebook ad
campaigns.

Each campaign object in the JSON array includes the following keys:

- campaign_id: A unique identifier for the campaign.
- budget: The total amount spent on the campaign.
- impressions: The number of times the ad was displayed.
- clicks: The number of clicks the ad received.
- conversions: The number of conversions generated by the campaign.

Your task is to compute the Cost Per Click (CPC) for each campaign using the
formula:

    CPC = budget / clicks

Then output the top 3 most cost-effective campaigns by displaying the
campaign_id and the computed CPC. The campaigns should be sorted in ascending
order by CPC (i.e., lower CPC is more cost-effective).
"""

import json

def top_3_campaigns(file_name):
    # list of (cost per click, campaign_id) tuples
    campaigns = []

    with open(file_name, 'r') as f:
        data = json.load(f)
        for campaign in data:
            # handle case where clicks is zero to avoid division by zero
            if campaign['clicks'] == 0:
                cpc = float('inf')
            else:
                cpc = campaign['budget'] / campaign['clicks']
            # store (CPC, campaign_id) tuple
            campaigns.append((cpc, campaign['campaign_id']))

    # sort by CPC (ascending)
    campaigns.sort()
    # print top 3 most cost-effective campaigns
    for cpc, campaign_id in campaigns[:3]:
        print(f"Campaign ID: {campaign_id}, Cost per Click: {cpc:.2f}")

top_3_campaigns('fb_campaigns.json')